package com.framework.interfaces;

import com.framework.data.Dummy;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.*;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Retention(RUNTIME)
@Target({ TYPE, METHOD, CONSTRUCTOR })
/**
 * @author abhola
 *
 */
public @interface JsonData {
    String jsonPath();
    Class<?> className() default Dummy.class;
    String useAutoGeneratedFileName() default "N";
}
